# Pratice for Numpy

In [1]:
# import numpy library
import numpy as np
food =  np.array(["Pakora","samosa","raita"])
food

array(['Pakora', 'samosa', 'raita'], dtype='<U6')

In [2]:
type(food)

numpy.ndarray

In [3]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
# Length function
len(food)

3

In [5]:
len(price)

3

In [6]:
price[2]

5

In [7]:
price.mean()

5.0

In [8]:
zero = np.zeros(6)
zero

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [13]:
# table of 8
np.arange(8,88,8)

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

# table of 10

In [14]:
np.arange(10,110,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])